project:
  type: book
  output-dir: docs

book:
  title: "pos-pln"
  author: "Bruno Machado"
  date: "12/31/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - js_go.qmd
    - dl1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt



